- name: Check running status
  stat:
    path: '{{ HOME }}/running'
  register: running_stat
  tags: run

- name: Run kube-worker
  include: run.yml
  when: running_stat.stat.exists == False
  tags: run
