- name: Copy join command to worker
  copy:
    src: '{{ LOCAL_DIR }}/kubeadm_join.sh'
    dest: '{{ HOME }}/'
    mode: 0755

- name: Join cluster
  shell: 'bash {{ HOME }}/kubeadm_join.sh'

- name: Create running flag
  file:
    path: '{{ HOME }}/running'
    state: touch
