- name: Start kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Start dockerd
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon-reload: yes
